github_username: arafatm
# markdown: GFM
# highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-remote-theme # Support leap-day theme

remote_theme: pages-themes/leap-day@v0.2.0 # https://github.com/pages-themes/leap-day

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# - jekyll-wikirefs # Not supported by GHP https://pages.github.com/versions/
#GFM:
#  input: GFM
#  toc:
#    min_level: 2
#    max_level: 5

# defaults:
#   - scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: page
#   - scope:
#       path: "assets/img"
#     values:
#       image: true
# 
# collections:
#   articles:
#     output: true
#     permalink: /:categories/:name

